### ISSUE TITLE
关于 "duratium_ingot"译名的一些建议。

### ISSUE THREAD

**Issue by CHN-YunRu** [OakPlatinum/Oritech#3]
### Issue description

"duratium_ingot"由下界合金锭和铂锭合金化后铸成，ium和um一般为金属元素的词缀，durat(i)即duration，有持续时间、期间之意。个人认为duratium可以译为昶铂 (合金)。昶，日长也。——《说文解字·新附》，可理解为永恒。再者，下界合金锭产自下界，昶从字形来看由“永日”构成，无论是字形还是含义都符合下界的特征。

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

无

### Fabric API version

无

### Oritech version

无

**Comment by OakPlatinum** [comment]
收到
这个我已经在作者新开的[Crowdin](https://crowdin.com/editor/oritech/16/en-zhcn?view=comfortable&filter=basic&value=0)上改了，但作者已经锁定了中文翻译，所以可能不能在下个版本即时显示
我去问问作者能不能给个Proofreader权限

btw，mc百科资料上的中文译名你打算更新吗？你要是不更新我就去更一下

**Comment by OakPlatinum** [comment]
以后翻译字符串的问题可以在Crowdin上直接改，教程书的翻译问题放到这里就行
